package de.openhpi.capstone1.game.constants;

public enum Event {
	
	MOUSECLICKLEFT, MOUSECLICKRIGHT, MOUSEMOVE, 
	RIGHTEND, LEFTEND, TOPEND, BOTTOMEND, 
	FIREHIT, BOMBHIT,
	SPEEDUP,
	SETSUPER, 
	SUPERMODEON, SUPERMODEOFF,
	ENDOFFRAME;

}
